### ISSUE TITLE
Check before update data and model

### ISSUE THREAD

**Issue by andazhao** [microsoft/llmops-promptflow-template#71]
Hi Team,

Is it possible to add some check before update dataset and model. Currently each commit will create new vision of model/dataset. I thought create_or_update command will check before update. But looks like it will update vision all the time. Thank you.

Anda

**Comment by andazhao** [comment]
![image](https://github.com/microsoft/llmops-promptflow-template/assets/19143213/8a7f8f7b-34f7-4208-b652-2e811867ec18)

**Comment by ritesh-modi** [comment]
This has been implemented now. https://github.com/microsoft/llmops-promptflow-template/pull/78
